version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /python/docker-credentials/sonal1996
    DOCKER_REGISTRY_PASSWORD: /python/docker-credentials/passward
    DOCKER_REGISTRY_URL: /python/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - git clone https://github.com/sudo19/simple-python-app-demo
      - echo "Building Docker image..."
      - echo "/python/docker-credentials/passward" | docker login -u "/python/docker-credentials/sonal1996" --password-stdin "/python/docker-registry/url"
      - docker build -t "/python/docker-credentials/sonal1996/python/docker-credentials/sonal1996/simple-python-app-demo:latest" simple-python-app-demo
      - docker push "/python/docker-registry/url/python/docker-credentials/sonal1996/simple-python-app-demo:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app-demo
